blank_issues_enabled: false
contact_links:
  - name: Configuration help?
    url: https://github.com/patterned-designs/readme/blob/main/README.md
    about: Please create a discussion.
  - name: Environment help?
    url: https://github.com/patterned-designs/readme/blob/main/README.md
    about: Please open a ticket.
  - name: Security concern?
    url: https://github.com/patterned-designs/readme/blob/main/README.md
    about: Please read the repository security organization