name: ❌ Bug Report
description: Report an issue in the module. **Do not** disclose security isuses in bug reports.
title: "Bug: Problem with the module"
labels: ["Bug"]
body:
  - type: markdown
    attributes:
      value: |
         ### ❗️ Read this before submitting your bug report:
         - **Write in English.** - Reports in all other languages will be closed.
         - **Provide as much detail as possible** - Error logs, screenshots, your exact configuration. If the issue cannot be reproduced, it cannot be fixed.
         - **Follow the [bug report guidelines](https://github.com/patterned-designs/terraform-null-test/blob/main/.github/SUPPORT.md).** - This will help maintainers qualify your report faster.
         - **Avoid posting errors or stacktraces without context** - Stack traces & errors aren't always enough to know what was happening when it failed.
  - type: checkboxes
    attributes:
      label: Prerequisites
      options:
        - label: I understand and accept the project's [code of conduct](https://github.com/patterned-designs/terraform-null-test/blob/main/.github/CODE_OF_CONDUCT.md).
          required: true
        - label: I have already [reviewed the project's documentation](https://github.com/patterned-designs/terraform-null-test/tree/main/docs) and found no solution to the issue.
          required: true
        - label: I have already [searched in existing issues](https://github.com/patterned-designs/terraform-null-test/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.
          required: true
  - type: dropdown
    id: terraform-version
    attributes:
      label: Terraform version
      description: |-
        You can find it by running `terraform version`.
      options:
        - v1.5.0
        - v1.5.1
        - v1.6.0
        - v1.6.1
        - v1.6.2
    validations:
      required: true
  - type: dropdown
    id: module-version
    attributes:
      label: Module version
      description: |-
        You can find it by checking your source or version reference.

        module "example" {
          source  = "patterned-designs/terraform-aws-codepipeline-terraform-executor"
          version = "1.2.1" # <== This value
        }
      options:
        - v0.1.2
        - v0.1.3
        - v0.1.4
        - v0.2.0
        - v0.2.1
    validations:
      required: true
  - type: input
    id: sponsor-company
    attributes:
      label: Your company or customer's name goes here (if applicable).
    validations:
      required: false
  - type: textarea
    id: problem
    attributes:
      label: "What's the problem?"
      placeholder: "The S3 bucket fails on create..."
    validations:
      required: true
